### ISSUE TITLE
Fatal Error replying to comments in Comment Mail Lite

### ISSUE THREAD

**Issue by raamdev** [websharks/comment-mail#297]
_This bug was originally reported on the WordPress Support Forum [here](https://wordpress.org/support/topic/fatal-error-2259?replies=2#post-8780382) and [here](https://wordpress.org/support/topic/what-does-comment-mail-do-after-wp-46-update-when-answering-comments?replies=4#post-8789477) and [here](https://wordpress.org/support/topic/error-replying-to-comments-when-logged-in-to-wp-admin?replies=2#post-8790327) and [here](https://wordpress.org/support/topic/error-message-received-when-replying-to-comments-on-blog?replies=2#post-8793034)._

----

The following appears when replying to comments on the site as a logged-in admin using Comment Mail Lite v160818:

![2016-08-23_23-37-02](https://cloud.githubusercontent.com/assets/53005/17917438/932af9da-698a-11e6-9111-b1d349bb20c3.png)

```
Fatal error: Uncaught exception 'Exception' with message 'Undefined overload property: `utils_rve`.' in /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/AbsBase.php:111
Stack trace:
#0 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/Plugin.php(866): WebSharks\CommentMail\AbsBase->__get('utils_rve')
#1 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/UtilsPhp.php(87) : eval()'d code(109): WebSharks\CommentMail\Plugin->__get('utils_rve')
#2 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/UtilsPhp.php(87): eval()
#3 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/Template.php(149): WebSharks\CommentMail\UtilsPhp->evaluate('<?php\nnamespace...', Array)
#4 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/QueueProcessor.php(898): WebSharks\CommentMail\Template->parse(Array)
#5 /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/QueuePr in /vagrant/src/app/src/wp/wp-content/plugins/comment-mail/src/includes/classes/AbsBase.php on line 111
```

This appears to be related to something that is expecting the RVE code to be present, likely the result of the work done in https://github.com/websharks/comment-mail/issues/285 for the last release. 

----

Additionally, when replying to comments from the WordPress Dashboard, the following shows up under the comment box. The comment reply goes through, but the JavaScript that refreshes the form fails and makes it look like the reply did not go through:

![2016-08-23_23-39-11](https://cloud.githubusercontent.com/assets/53005/17917462/d3041b90-698a-11e6-8187-a406fa54df07.png)

----

# Temporary Workaround

At this time the only workaround is rolling back to the previous version of Comment Mail Lite, [v160618](http://comment-mail.com/release-archive/).

**Comment by raamdev** [comment]
Next Release Changelog:

- **Bug Fix**: Fixed a bug that was generating a fatal error when replying to comments. This bug only affected the Lite version of Comment Mail and was introduced by the previous release (v160818) where [work](https://github.com/websharks/comment-mail/issues/285) was done to strip out unused Pro-only code from the Lite codebase. A few references to Pro-only functions were missed and that resulted in fatal errors for the Lite version in some scenarios. See [Issue #297](https://github.com/websharks/comment-mail/issues/297).

**Comment by raamdev** [comment]
**Comment Mail v160824** has been released and includes changes from this GitHub Issue. See the [v160824 announcement](http://comment-mail.com/comment-mail-lite-v160824-maintenance-release/) for further details.

---

This issue will now be locked to further updates. If you have something to add related to this GitHub Issue, please open a new GitHub Issue and reference this one (#297).
